name: Publish Module to PSGallery

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PowerShellGet
        run: |
          Install-Module -Name PowerShellGet -Force -Scope CurrentUser
          Import-Module -Name PowerShellGet
        shell: pwsh

      - name: Publish Module
        run: |
          $PSGalleryApiKey = "${{ secrets.PSGALLERY_API_KEY }}"
          Publish-Module -Path ./ -NuGetApiKey $PSGalleryApiKey
        shell: pwsh
